"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { FaArrowDown, FaArrowUp, FaChartLine, FaFileInvoiceDollar, FaHandHoldingUsd, FaMoneyCheckAlt, FaShieldAlt, FaWallet } from "react-icons/fa";
import { supabase } from "@/lib/supabase";
import { CurrentMembership, getCurrentMembership } from "@/lib/current-user";

type Summary={sales:number;collected:number;receivable:number;expenses:number;deposits_held:number;owner_payables:number;partner_payables:number;open_settlements:number;unclosed_days:number;ledger_count:number};
type Villa={id:string;name:string};
type Reservation={id:string;reservation_code:string;guest_name:string;villa_id:string;grand_total:number;paid_total:number;balance:number;currency:string;check_in:string;check_out:string;status:string};
type Deposit={id:string;reservation_id:string;guest_name:string|null;amount:number;refunded_amount:number;withheld_amount:number;currency:string;status:string;created_at:string};
type Settlement={id:string;settlement_type:string;period_start:string;period_end:string;currency:string;gross_amount:number;deductions:number;payable_amount:number;paid_amount:number;status:string;due_date:string|null;note:string|null;created_at:string};
type DayClose={id:string;close_date:string;currency:string;opening_balance:number;cash_in:number;cash_out:number;expected_closing:number;actual_closing:number;difference:number;status:string;closed_at:string};
type Ledger={id:string;entry_type:string;direction:string;amount:number;currency:string;description:string|null;occurred_at:string;reservation_id:string|null};

const today=()=>new Date().toISOString().slice(0,10);
const monthStart=()=>`${today().slice(0,7)}-01`;
const money=(v:number,c="TRY")=>new Intl.NumberFormat("tr-TR",{style:"currency",currency:c,maximumFractionDigits:2}).format(Number(v||0));
const input="w-full rounded-xl border border-white/10 bg-[#07111f] px-3 py-3 text-sm text-white outline-none focus:border-violet-400/50";
const label="mb-1.5 block text-[11px] font-black uppercase tracking-wide text-slate-400";

export default function VillaFinanceCenterPage(){
 const [membership,setMembership]=useState<CurrentMembership|null>(null);
 const [summary,setSummary]=useState<Summary|null>(null);
 const [villas,setVillas]=useState<Villa[]>([]);
 const [reservations,setReservations]=useState<Reservation[]>([]);
 const [deposits,setDeposits]=useState<Deposit[]>([]);
 const [settlements,setSettlements]=useState<Settlement[]>([]);
 const [closes,setCloses]=useState<DayClose[]>([]);
 const [ledger,setLedger]=useState<Ledger[]>([]);
 const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [message,setMessage]=useState("");
 const [range,setRange]=useState({start:monthStart(),end:today()});
 const [depositForm,setDepositForm]=useState({reservationId:"",amount:"",status:"received",note:""});
 const [refundForm,setRefundForm]=useState({depositId:"",refundAmount:"",withheldAmount:"0",reason:""});
 const [closeForm,setCloseForm]=useState({date:today(),actualClosing:"",note:""});
 const [ledgerForm,setLedgerForm]=useState({type:"adjustment",direction:"credit",amount:"",description:"",reservationId:""});

 const load=useCallback(async()=>{
  setLoading(true);setError("");
  try{
   const {data:{user}}=await supabase.auth.getUser(); if(!user)return;
   const current=await getCurrentMembership(user.id); if(!current)return; setMembership(current);
   const cid=current.company_id;
   const [s,v,r,d,st,dc,l]=await Promise.all([
    supabase.rpc("get_villa_finance_pro_summary",{p_company_id:cid,p_start:range.start,p_end:range.end}),
    supabase.from("villas").select("id,name").eq("company_id",cid).eq("is_active",true).order("name"),
    supabase.from("villa_reservations").select("id,reservation_code,guest_name,villa_id,grand_total,paid_total,balance,currency,check_in,check_out,status").eq("company_id",cid).order("check_in",{ascending:false}).limit(150),
    supabase.from("villa_security_deposits").select("id,reservation_id,guest_name,amount,refunded_amount,withheld_amount,currency,status,created_at").eq("company_id",cid).order("created_at",{ascending:false}).limit(100),
    supabase.from("villa_settlements").select("id,settlement_type,period_start,period_end,currency,gross_amount,deductions,payable_amount,paid_amount,status,due_date,note,created_at").eq("company_id",cid).order("created_at",{ascending:false}).limit(100),
    supabase.from("villa_day_closes").select("id,close_date,currency,opening_balance,cash_in,cash_out,expected_closing,actual_closing,difference,status,closed_at").eq("company_id",cid).order("close_date",{ascending:false}).limit(45),
    supabase.from("villa_finance_ledger").select("id,entry_type,direction,amount,currency,description,occurred_at,reservation_id").eq("company_id",cid).order("occurred_at",{ascending:false}).limit(150),
   ]);
   const err=[s,v,r,d,st,dc,l].find(x=>x.error)?.error; if(err)throw err;
   setSummary((s.data||null) as Summary|null); setVillas((v.data||[]) as Villa[]); setReservations((r.data||[]) as Reservation[]); setDeposits((d.data||[]) as Deposit[]); setSettlements((st.data||[]) as Settlement[]); setCloses((dc.data||[]) as DayClose[]); setLedger((l.data||[]) as Ledger[]);
   const first=(r.data?.[0] as Reservation|undefined)?.id||""; setDepositForm(x=>({...x,reservationId:x.reservationId||first})); setLedgerForm(x=>({...x,reservationId:x.reservationId||first}));
  }catch(e){setError(e instanceof Error?e.message:"Finans merkezi yüklenemedi.");} finally{setLoading(false);}
 },[range.start,range.end]);
 useEffect(()=>{void load();},[load]);

 const reservationMap=useMemo(()=>new Map(reservations.map(r=>[r.id,r])),[reservations]);
 const cards=[
  ["Toplam Satış",summary?.sales||0,FaChartLine],["Tahsil Edilen",summary?.collected||0,FaArrowDown],["Müşteri Bakiyesi",summary?.receivable||0,FaMoneyCheckAlt],["Giderler",summary?.expenses||0,FaArrowUp],
  ["Emanet Depozito",summary?.deposits_held||0,FaShieldAlt],["Malik Hakedişi",summary?.owner_payables||0,FaHandHoldingUsd],["Partner Hakedişi",summary?.partner_payables||0,FaHandHoldingUsd],
 ] as Array<[string,number,React.ComponentType<{className?:string}>]>;

 async function addDeposit(e:FormEvent){e.preventDefault(); if(!membership||!depositForm.reservationId||!depositForm.amount)return; setBusy(true);setError("");setMessage(""); const r=reservationMap.get(depositForm.reservationId); const {error:er}=await supabase.from("villa_security_deposits").upsert({company_id:membership.company_id,villa_id:r?.villa_id,reservation_id:depositForm.reservationId,guest_name:r?.guest_name||null,amount:Number(depositForm.amount),currency:r?.currency||"TRY",status:depositForm.status,received_at:depositForm.status==="received"?new Date().toISOString():null,note:depositForm.note||null},{onConflict:"reservation_id"}); if(er)setError(er.message);else{setMessage("Depozito kaydı güncellendi.");setDepositForm(x=>({...x,amount:"",note:""}));await load();}setBusy(false);}
 async function updateDeposit(e:FormEvent){e.preventDefault(); if(!refundForm.depositId)return; setBusy(true);setError(""); const dep=deposits.find(x=>x.id===refundForm.depositId); if(!dep){setBusy(false);return;} const refund=Number(refundForm.refundAmount||0), withheld=Number(refundForm.withheldAmount||0); const status=refund>=dep.amount?"refunded":withheld>0?"withheld":refund>0?"partially_refunded":dep.status; const {error:er}=await supabase.from("villa_security_deposits").update({refunded_amount:refund,withheld_amount:withheld,withholding_reason:refundForm.reason||null,status,refund_at:refund>0?new Date().toISOString():null,updated_at:new Date().toISOString()}).eq("id",dep.id); if(er)setError(er.message);else{setMessage("Depozito iade/mahsup bilgisi güncellendi.");await load();}setBusy(false);}
 async function closeDay(e:FormEvent){e.preventDefault(); if(!membership||!closeForm.actualClosing)return; setBusy(true);setError(""); const {error:er}=await supabase.rpc("close_villa_finance_day",{p_company_id:membership.company_id,p_close_date:closeForm.date,p_actual_closing:Number(closeForm.actualClosing),p_currency:"TRY",p_note:closeForm.note||null}); if(er)setError(er.message);else{setMessage("Gün sonu kapatıldı.");setCloseForm(x=>({...x,actualClosing:"",note:""}));await load();}setBusy(false);}
 async function addLedger(e:FormEvent){e.preventDefault(); if(!membership||!ledgerForm.amount)return; setBusy(true);setError(""); const {error:er}=await supabase.rpc("record_villa_finance_entry",{p_company_id:membership.company_id,p_entry_type:ledgerForm.type,p_direction:ledgerForm.direction,p_amount:Number(ledgerForm.amount),p_currency:"TRY",p_villa_id:null,p_reservation_id:ledgerForm.reservationId||null,p_owner_id:null,p_partner_company_id:null,p_reference_type:"manual",p_reference_id:null,p_description:ledgerForm.description||null}); if(er)setError(er.message);else{setMessage("Finans hareketi kaydedildi.");setLedgerForm(x=>({...x,amount:"",description:""}));await load();}setBusy(false);}

 if(loading)return <main className="flex min-h-[70vh] items-center justify-center bg-[#06101b] text-slate-400">Villa Finans Merkezi hazırlanıyor…</main>;
 return <main className="min-h-screen bg-[#06101b] p-5 text-white lg:p-7"><div className="mx-auto max-w-[1750px]">
  <div className="flex flex-wrap items-start justify-between gap-4"><div><div className="text-[10px] font-black uppercase tracking-[.28em] text-violet-300">TUROBUS VILLA OS · FINANCE PRO</div><h1 className="mt-2 text-3xl font-black">Villa Finans Komuta Merkezi</h1><p className="mt-2 max-w-3xl text-sm text-slate-500">Tahsilat, depozito, hakediş, cari hareket, gün sonu ve finans kontrolü tek ekranda.</p></div><div className="flex gap-2"><Link href="/dashboard/villa-os/erp" className="rounded-xl border border-white/10 px-4 py-3 text-xs font-black text-slate-300">Villa ERP</Link><button onClick={()=>void load()} className="rounded-xl bg-violet-400 px-4 py-3 text-xs font-black text-slate-950">Yenile</button></div></div>
  <div className="mt-5 grid gap-3 md:grid-cols-[1fr_1fr_auto]"><label><span className={label}>Rapor Başlangıç Tarihi</span><input type="date" className={input} value={range.start} onChange={e=>setRange(x=>({...x,start:e.target.value}))}/></label><label><span className={label}>Rapor Bitiş Tarihi</span><input type="date" className={input} value={range.end} onChange={e=>setRange(x=>({...x,end:e.target.value}))}/></label><div className="flex items-end"><button onClick={()=>void load()} className="h-[46px] rounded-xl border border-white/10 px-5 text-xs font-black">Raporu Güncelle</button></div></div>
  {error&&<div className="mt-4 rounded-xl bg-red-500/10 p-4 text-sm text-red-300">{error}</div>}{message&&<div className="mt-4 rounded-xl bg-emerald-500/10 p-4 text-sm text-emerald-300">{message}</div>}
  <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-7">{cards.map(([t,v,Icon])=><div key={t} className="rounded-2xl border border-white/[.07] bg-[#091724] p-4"><div className="flex items-center justify-between"><span className="text-[10px] font-black uppercase text-slate-500">{t}</span><Icon className="text-violet-300"/></div><div className="mt-3 text-xl font-black">{money(v)}</div></div>)}</div>
  <div className="mt-4 grid gap-3 md:grid-cols-3"><div className="rounded-2xl border border-white/[.07] bg-[#091724] p-5"><div className="text-xs text-slate-500">Açık Hakediş</div><div className="mt-2 text-3xl font-black">{summary?.open_settlements||0}</div></div><div className="rounded-2xl border border-white/[.07] bg-[#091724] p-5"><div className="text-xs text-slate-500">Kapanmamış Gün</div><div className="mt-2 text-3xl font-black">{summary?.unclosed_days||0}</div></div><div className="rounded-2xl border border-white/[.07] bg-[#091724] p-5"><div className="text-xs text-slate-500">Defter Hareketi</div><div className="mt-2 text-3xl font-black">{summary?.ledger_count||0}</div></div></div>

  <div className="mt-6 grid gap-5 2xl:grid-cols-2">
   <section className="rounded-2xl border border-white/[.07] bg-[#091724] p-5"><div className="flex items-center gap-2"><FaShieldAlt className="text-violet-300"/><h2 className="font-black">Depozito / Hasar Güvence Yönetimi</h2></div><form onSubmit={addDeposit} className="mt-4 grid gap-3 md:grid-cols-2"><label className="md:col-span-2"><span className={label}>Rezervasyon</span><select className={input} value={depositForm.reservationId} onChange={e=>setDepositForm(x=>({...x,reservationId:e.target.value}))}>{reservations.map(r=><option key={r.id} value={r.id}>{r.reservation_code} · {r.guest_name}</option>)}</select></label><label><span className={label}>Depozito Tutarı (TL)</span><input type="number" className={input} value={depositForm.amount} onChange={e=>setDepositForm(x=>({...x,amount:e.target.value}))} placeholder="Örn. 5000"/></label><label><span className={label}>Depozito Durumu</span><select className={input} value={depositForm.status} onChange={e=>setDepositForm(x=>({...x,status:e.target.value}))}><option value="expected">Bekleniyor</option><option value="received">Tahsil Edildi</option></select></label><label className="md:col-span-2"><span className={label}>Depozito Notu</span><input className={input} value={depositForm.note} onChange={e=>setDepositForm(x=>({...x,note:e.target.value}))} placeholder="Örn. Girişte nakit teslim alındı"/></label><button disabled={busy} className="md:col-span-2 rounded-xl bg-violet-400 py-3 font-black text-slate-950">Depozito Kaydet</button></form></section>

   <section className="rounded-2xl border border-white/[.07] bg-[#091724] p-5"><div className="flex items-center gap-2"><FaWallet className="text-violet-300"/><h2 className="font-black">Gün Sonu / Kasa Kapama</h2></div><form onSubmit={closeDay} className="mt-4 grid gap-3 md:grid-cols-2"><label><span className={label}>Kapanış Tarihi</span><input type="date" className={input} value={closeForm.date} onChange={e=>setCloseForm(x=>({...x,date:e.target.value}))}/></label><label><span className={label}>Fiili Kasa Bakiyesi (TL)</span><input type="number" className={input} value={closeForm.actualClosing} onChange={e=>setCloseForm(x=>({...x,actualClosing:e.target.value}))} placeholder="Kasada sayılan gerçek tutar"/></label><label className="md:col-span-2"><span className={label}>Gün Sonu Açıklaması</span><input className={input} value={closeForm.note} onChange={e=>setCloseForm(x=>({...x,note:e.target.value}))} placeholder="Varsa fark veya vardiya notu"/></label><button disabled={busy} className="md:col-span-2 rounded-xl bg-violet-400 py-3 font-black text-slate-950">Günü Kapat</button></form></section>
  </div>

  <div className="mt-5 grid gap-5 2xl:grid-cols-[430px_1fr]">
   <section className="rounded-2xl border border-white/[.07] bg-[#091724] p-5"><div className="flex items-center gap-2"><FaFileInvoiceDollar className="text-violet-300"/><h2 className="font-black">Manuel Finans / Cari Hareket</h2></div><form onSubmit={addLedger} className="mt-4 space-y-3"><label><span className={label}>Hareket Türü</span><select className={input} value={ledgerForm.type} onChange={e=>setLedgerForm(x=>({...x,type:e.target.value}))}><option value="adjustment">Düzeltme / Cari İşlem</option><option value="collection">Tahsilat</option><option value="expense">Gider</option><option value="owner_payment">Villa Sahibi Ödemesi</option><option value="partner_payment">Partner Ödemesi</option><option value="commission">Komisyon</option></select></label><label><span className={label}>Borç / Alacak Yönü</span><select className={input} value={ledgerForm.direction} onChange={e=>setLedgerForm(x=>({...x,direction:e.target.value}))}><option value="credit">Alacak / Giriş</option><option value="debit">Borç / Çıkış</option></select></label><label><span className={label}>Bağlı Rezervasyon</span><select className={input} value={ledgerForm.reservationId} onChange={e=>setLedgerForm(x=>({...x,reservationId:e.target.value}))}><option value="">Rezervasyona bağlı değil</option>{reservations.map(r=><option key={r.id} value={r.id}>{r.reservation_code} · {r.guest_name}</option>)}</select></label><label><span className={label}>Tutar (TL)</span><input type="number" className={input} value={ledgerForm.amount} onChange={e=>setLedgerForm(x=>({...x,amount:e.target.value}))} placeholder="Örn. 2500"/></label><label><span className={label}>İşlem Açıklaması</span><input className={input} value={ledgerForm.description} onChange={e=>setLedgerForm(x=>({...x,description:e.target.value}))} placeholder="İşlemin nedenini açıkça yazın"/></label><button disabled={busy} className="w-full rounded-xl bg-violet-400 py-3 font-black text-slate-950">Finans Hareketi Kaydet</button></form></section>
   <section className="overflow-hidden rounded-2xl border border-white/[.07] bg-[#091724]"><div className="border-b border-white/[.07] px-5 py-4 font-black">Finans Defteri · Son Hareketler</div><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead className="bg-white/[.03] text-left text-[10px] uppercase text-slate-500"><tr><th className="px-4 py-3">Tarih</th><th className="px-4 py-3">Tür</th><th className="px-4 py-3">Yön</th><th className="px-4 py-3">Tutar</th><th className="px-4 py-3">Rezervasyon</th><th className="px-4 py-3">Açıklama</th></tr></thead><tbody>{ledger.map(x=><tr key={x.id} className="border-t border-white/[.05]"><td className="px-4 py-3">{new Date(x.occurred_at).toLocaleString("tr-TR")}</td><td className="px-4 py-3">{x.entry_type}</td><td className="px-4 py-3">{x.direction==="credit"?"Alacak / Giriş":"Borç / Çıkış"}</td><td className="px-4 py-3 font-black">{money(x.amount,x.currency)}</td><td className="px-4 py-3">{x.reservation_id?reservationMap.get(x.reservation_id)?.reservation_code||"—":"—"}</td><td className="px-4 py-3 text-slate-400">{x.description||"—"}</td></tr>)}</tbody></table></div></section>
  </div>

  <div className="mt-5 grid gap-5 2xl:grid-cols-2">
   <section className="overflow-hidden rounded-2xl border border-white/[.07] bg-[#091724]"><div className="border-b border-white/[.07] px-5 py-4 font-black">Depozito Listesi</div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="bg-white/[.03] text-left text-[10px] uppercase text-slate-500"><tr><th className="px-4 py-3">Misafir</th><th className="px-4 py-3">Tutar</th><th className="px-4 py-3">İade</th><th className="px-4 py-3">Kesinti</th><th className="px-4 py-3">Durum</th></tr></thead><tbody>{deposits.map(x=><tr key={x.id} className="border-t border-white/[.05]"><td className="px-4 py-3">{x.guest_name||reservationMap.get(x.reservation_id)?.guest_name||"—"}</td><td className="px-4 py-3">{money(x.amount,x.currency)}</td><td className="px-4 py-3">{money(x.refunded_amount,x.currency)}</td><td className="px-4 py-3">{money(x.withheld_amount,x.currency)}</td><td className="px-4 py-3">{x.status}</td></tr>)}</tbody></table></div></section>
   <section className="rounded-2xl border border-white/[.07] bg-[#091724] p-5"><h2 className="font-black">Depozito İade / Kesinti</h2><form onSubmit={updateDeposit} className="mt-4 grid gap-3 md:grid-cols-2"><label className="md:col-span-2"><span className={label}>Depozito Kaydı</span><select className={input} value={refundForm.depositId} onChange={e=>setRefundForm(x=>({...x,depositId:e.target.value}))}><option value="">Depozito seçin</option>{deposits.map(d=><option key={d.id} value={d.id}>{d.guest_name||reservationMap.get(d.reservation_id)?.guest_name||"Misafir"} · {money(d.amount,d.currency)}</option>)}</select></label><label><span className={label}>Toplam İade Tutarı</span><input type="number" className={input} value={refundForm.refundAmount} onChange={e=>setRefundForm(x=>({...x,refundAmount:e.target.value}))} placeholder="İade edilen toplam"/></label><label><span className={label}>Kesilen / Mahsup Edilen Tutar</span><input type="number" className={input} value={refundForm.withheldAmount} onChange={e=>setRefundForm(x=>({...x,withheldAmount:e.target.value}))}/></label><label className="md:col-span-2"><span className={label}>Kesinti Nedeni</span><input className={input} value={refundForm.reason} onChange={e=>setRefundForm(x=>({...x,reason:e.target.value}))} placeholder="Örn. Hasarlı sandalye bedeli"/></label><button disabled={busy} className="md:col-span-2 rounded-xl bg-violet-400 py-3 font-black text-slate-950">İade / Kesintiyi Kaydet</button></form></section>
  </div>

  <div className="mt-5 grid gap-5 2xl:grid-cols-2"><section className="overflow-hidden rounded-2xl border border-white/[.07] bg-[#091724]"><div className="border-b border-white/[.07] px-5 py-4 font-black">Hakedişler</div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="bg-white/[.03] text-left text-[10px] uppercase text-slate-500"><tr><th className="px-4 py-3">Tür</th><th className="px-4 py-3">Dönem</th><th className="px-4 py-3">Brüt</th><th className="px-4 py-3">Kesinti</th><th className="px-4 py-3">Ödenecek</th><th className="px-4 py-3">Durum</th></tr></thead><tbody>{settlements.map(x=><tr key={x.id} className="border-t border-white/[.05]"><td className="px-4 py-3">{x.settlement_type==="owner"?"Villa Sahibi":"Partner"}</td><td className="px-4 py-3">{x.period_start} → {x.period_end}</td><td className="px-4 py-3">{money(x.gross_amount,x.currency)}</td><td className="px-4 py-3">{money(x.deductions,x.currency)}</td><td className="px-4 py-3 font-black">{money(x.payable_amount-x.paid_amount,x.currency)}</td><td className="px-4 py-3">{x.status}</td></tr>)}</tbody></table></div></section><section className="overflow-hidden rounded-2xl border border-white/[.07] bg-[#091724]"><div className="border-b border-white/[.07] px-5 py-4 font-black">Gün Sonu Geçmişi</div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="bg-white/[.03] text-left text-[10px] uppercase text-slate-500"><tr><th className="px-4 py-3">Tarih</th><th className="px-4 py-3">Açılış</th><th className="px-4 py-3">Giriş</th><th className="px-4 py-3">Çıkış</th><th className="px-4 py-3">Beklenen</th><th className="px-4 py-3">Fiili</th><th className="px-4 py-3">Fark</th></tr></thead><tbody>{closes.map(x=><tr key={x.id} className="border-t border-white/[.05]"><td className="px-4 py-3">{x.close_date}</td><td className="px-4 py-3">{money(x.opening_balance,x.currency)}</td><td className="px-4 py-3">{money(x.cash_in,x.currency)}</td><td className="px-4 py-3">{money(x.cash_out,x.currency)}</td><td className="px-4 py-3">{money(x.expected_closing,x.currency)}</td><td className="px-4 py-3">{money(x.actual_closing,x.currency)}</td><td className={`px-4 py-3 font-black ${Math.abs(x.difference)>0.01?"text-amber-300":"text-emerald-300"}`}>{money(x.difference,x.currency)}</td></tr>)}</tbody></table></div></section></div>
 </div></main>;
}
